/**
 * Curated list of major Philippine cities and municipalities.
 */
export const PH_CITIES: string[] = [
  // Metro Manila (NCR)
  'Caloocan',
  'Las Piñas',
  'Makati',
  'Malabon',
  'Mandaluyong',
  'Manila',
  'Marikina',
  'Muntinlupa',
  'Navotas',
  'Parañaque',
  'Pasay',
  'Pasig',
  'Pateros',
  'Quezon City',
  'San Juan',
  'Taguig',
  'Valenzuela',

  // Major Provincial Cities & Capitals
  'Angeles',
  'Antipolo',
  'Bacolod',
  'Baguio',
  'Batangas City',
  'Biñan',
  'Cagayan de Oro',
  'Calamba',
  'Cabuyao',
  'Cavite City',
  'Cebu City',
  'Cotabato City',
  'Dagupan',
  'Dasmariñas',
  'Davao City',
  'Dumaguete',
  'General Santos',
  'Iligan',
  'Iloilo City',
  'Imus',
  'Lapu-Lapu',
  'Legazpi',
  'Lipa',
  'Mandaue',
  'Naga',
  'Olongapo',
  'Ormoc',
  'Puerto Princesa',
  'Roxas City',
  'San Fernando (Pampanga)',
  'San Fernando (La Union)',
  'San Jose del Monte',
  'Santa Rosa',
  'Tacloban',
  'Tagaytay',
  'Tagbilaran',
  'Tagum',
  'Tarlac City',
  'Trece Martires',
  'Zamboanga City',
];
